#
# https://circleci.com/docs/2.0/language-php/
#

version: 2
jobs:
  build:
    docker:
    - image: circleci/php:7.1.20-cli-stretch

    working_directory: ~/aire

    steps:
    - checkout

    - run:
        name: Enable XDebug
        command: sudo docker-php-ext-enable xdebug

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "composer.json" }}
        - v1-dependencies-

    - run:
        name: Install Composer dependencies
        command: "[ -f ./vendor/laravel/framework/composer.json ] || composer install -n --prefer-dist"

    - save_cache:
        paths:
        - ./vendor
        key: v1-dependencies-{{ checksum "composer.json" }}

    - run:
        name: Ensure artifacts directory exists
        command: mkdir -p ~/artifacts

    - run:
        name: Run tests
        command: ./vendor/bin/phpunit -c phpunit.xml --log-junit ~/artifacts/junit.xml --coverage-clover ~/artifacts/clover.xml

    - run:
        name: Send data to Coveralls
        command: php vendor/bin/php-coveralls -v -x ~/artifacts/clover.xml -o ~/artifacts/coveralls.json

    - store_test_results:
        path: ~/artifacts

    - store_artifacts:
        path: ~/artifacts

