#
# https://circleci.com/docs/2.0/language-php/
#

version: 2
jobs:
  build:
    docker:
    - image: circleci/php:7.2-cli-stretch

    working_directory: ~/aire

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "composer.json" }}
        - v1-dependencies-

    - run:
        name: Ensuring that the artifacts directory exists
        command: mkdir -p ~/artifacts

#    - run:
#        name: Write version number to JSON file for testing purposes
#        command: "cat composer.json | jq --arg version 1.999.999 '. + {version: $version}' > composer.test.json && mv composer.test.json composer.json && cat composer.json"

    - run:
        name: Installing Composer dependencies
        command: "composer install --dev --prefer-dist"

    - run:
        name: Install Laravel 5.8
        command: "composer require laravel/framework:^5.8 orchestra/testbench:^3.8"

    - run:
        name: Test on Laravel 5.8
        command: ./vendor/bin/phpunit -c phpunit.xml

    - run:
        name: Install Laravel 6.0
        command: "composer require --update-with-all-dependencies laravel/framework:^6.0 orchestra/testbench:^4.0"

    - run:
        name: Enable XDebug for test with coverage
        command: sudo docker-php-ext-enable xdebug

    - run:
        name: Test on Laravel 6.0
        command: ./vendor/bin/phpunit -c phpunit.xml --log-junit ~/artifacts/junit.xml --coverage-clover ~/artifacts/clover.xml

    - save_cache:
        paths:
          - ./vendor
        key: v1-dependencies-{{ checksum "composer.json" }}

    - run:
        name: Sending data to Coveralls
        command: php vendor/bin/php-coveralls -v -x ~/artifacts/clover.xml -o ~/artifacts/coveralls.json || echo 'Unable to upload to Coveralls...'

    - store_test_results:
        path: ~/artifacts

    - store_artifacts:
        path: ~/artifacts

