name: PHPUnit

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  php-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.4, 7.3, 7.2]
        laravel: [^7.0@dev, ^6.0, 5.8.*, 5.7.*]
        dependency-version: [prefer-lowest, prefer-stable]
        include:
          - laravel: ^7.0
            testbench: ^5.0
            minimum-stability: dev
          - laravel: ^6.0
            testbench: ^4.0
            minimum-stability: stable
          - laravel: 5.8.*
            testbench: 3.8.*
            minimum-stability: stable
          - laravel: 5.7.*
            testbench: 3.7.*
            minimum-stability: stable
        exclude:
          - laravel: 5.7.*
            php: 7.4

    name: "PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} (${{ matrix.dependency-version }})"

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php }}
          extension-csv: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Set minimum stability
        run: composer config minimum-stability ${{ matrix.minimum-stability }}

      - name: Install dependencies
        run: composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
        
      - name: Set dependency version
        run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

      - name: Execute tests
        run: vendor/bin/phpunit
